apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: LoadBalancer  # Use NodePort if not on a cloud provider
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 80         # The port that the service exposes
    targetPort: 4499 # The port the container is listening on

